routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $promotions = \App\Models\Promotion::orderBy('ref', 'desc')->get();

    $promotions = $promotions->filter(function ($promo, $key) {
        return $promo->products()->get()->count() > 1;
    })->take(2);

    return view('pages/home', compact('promotions'));

})->name('home');

Route::get('promocions', function () {

    $promotions = \App\Models\Promotion::orderBy('ref', 'desc')->get();

    return view('pages/promotions', compact('promotions'));

})->name('promotions');

Route::get('contacte', function () {

    return view('pages/contact');

})->name('contact');

Route::get('nosaltres', function () {
    
    return view('pages/about-us');

})->name('about-us');

Route::get('filtre', function () {

    $s = request()->all();

    $q = \App\Models\Product::where('mode', '=', (isset($s['mode'])) ? 'rent' : 'buy');

    if(isset($s['ref']))
    {
        $q = $q->where('external_src_reference', 'LIKE', '%' . $s['ref'] . '%');
    }

    if(isset($s['cities']) && count($s['cities']) > 0)
    {
        $q = $q->whereIn('city_id', array_map('intval', $s['cities']));
    }

    if(isset($s['types']) && count($s['types']) > 0)
    {
        $q = $q->whereIn('type_id', array_map('intval', $s['types']));
    }

    if(isset($s['extras']) && count($s['extras']) > 0)
    {
        foreach($s['extras'] as $extra)
        {
            if(in_array($extra, array_keys(config('site.extras'))))
            {
                $q = $q->where('extras->'. $extra , true);
            }
        }        
    }

    if(isset($s['option-room']))
    {
        $min = (int) explode('-', $s['option-room'])[1];
        $q = $q->where('external_src_rooms', '>=', $min);
    }

    if(isset($s['option-bathroom']))
    {
        $min = (int) explode('-', $s['option-bathroom'])[1];
        $q = $q->where('external_src_bathrooms', '>=', $min);
    }

    $results = $q->get();

    return view('pages/results', ['results' => $results]);

})->name('filter');

Route::get('analyze', function () {
    
    Artisan::call('product:refresh');

    // parsing file
    $url = env('PRODUCTS_XML_PATH', public_path('service/500212.xml'));
    $fileContents = file_get_contents($url);
    $fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
    $fileContents = trim(str_replace('"', "'", $fileContents));
    $simpleXml = simplexml_load_string($fileContents, "SimpleXMLElement", LIBXML_NOCDATA);
    $json = json_encode($simpleXml);
    $object = json_decode($json);
    $inmuebles = collect($object->Inmuebles->Inmueble);

    dump($inmuebles);

});

Route::get('test', function () {
    
    dump(App\Models\Promotion::all()->last()->image);

});


// keep this route last

Route::get('/{slug}/{ref}', function ($slug, $ref) {

    $product = \App\Models\Product::where('external_src_reference', $ref)->firstOrFail();

    if($slug != $product->slug)
        return redirect(route('product', ['slug' => $product->slug, 'ref' => $ref]));

    return view('pages/product', compact('product'));

})->name('product');

app/Models/Promotion.php
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Model;

class Promotion extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'promotions';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];


    public function getNumberAttribute()
    {
        return mb_substr(strrev($this->ref), 0, -2);
    }

    public function products()
    {
        return $this->hasMany(Product::class);
    }

    public function getLocationAttribute()
    {
       return $this->products()->get()->firstOrFail()->city()->first()->label;
    }


    public function getWcAttribute()
    {
        if($this->products()->get()->min('external_src_bathrooms') == $this->products()->get()->max('external_src_bathrooms')) {
            return $this->products()->get()->min('external_src_bathrooms');
        }
        return $this->products()->get()->min('external_src_bathrooms') .'-'. $this->products()->get()->max('external_src_bathrooms');
    }


    public function getAreaAttribute()
    {
        if($this->products()->get()->min('external_src_area') == $this->products()->get()->max('external_src_area')) {
            return round($this->products()->get()->min('external_src_area'));
        }
        return round($this->products()->get()->min('external_src_area')) .'-'. round($this->products()->get()->max('external_src_area'));
    }

    public function getRoomsAttribute()
    {
        if($this->products()->get()->min('external_src_rooms') == $this->products()->get()->max('external_src_rooms')) {
            return $this->products()->get()->min('external_src_rooms');
        }
        return $this->products()->get()->min('external_src_rooms') .'-'. $this->products()->get()->max('external_src_rooms');
    }

    public function getImageAttribute()
    {
        return $this->products()->orderBy('external_src_area', 'desc')->get()->first()->image;
    }

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESSORS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
}

resources/views/inc/promotion/article.blade.php
<article>

    <div class="d-flex justify-content-between">
        <div>
            <h1 class="pb-2 display display-4">{{ $promotion->location }}</h1>
        </div>
        <div class="promo-num">
            <div class="font-brand-alt font-brand-alt-1">promo</div>
            <div class="font-weight-bold display-2">{{ $promotion->number }}</div>
        </div>
    </div>

    <div class="btn-override text-center">
        <a href="{{ route('filter') }}?ref={{ $promotion->ref }}"><img src="{{ $promotion->image }}" class="img-fluid rounded-sm" alt=""></a>
        <a href="{{ route('filter') }}?ref={{ $promotion->ref }}" class="btn btn-secondary translate-m50">Més informació</a>
    </div>
    <div class="text-center">
        <div class="row pt-1 font-brand-alt font-brand-alt-1">
            <div class="col">
                Ref.
                <br>
                <span class="d-block font-brand-alt-2 mt-1">{{ $promotion->ref }}</span>
            </div>
            <div class="col border-left border-primary">
                M<sup class="small font-weight-bold">2</sup>
                <br>
                <span class="d-block font-brand-alt-2 mt-1">{{ $promotion->area }}</span>
            </div>
            <div class="col border-left border-primary">
                Hab.
                <br>
                <span class="d-block font-brand-alt-2 mt-1">{{ $promotion->rooms }}</span>
            </div>
            <div class="col border-left border-primary">
                WC
                <br>
                <span class="d-block font-brand-alt-2 mt-1">{{ $promotion->wc }}</span>
            </div>
        </div>

        <div class="pt-4">
            <p>
                Informa't de les nostres promocions residencials!
            </p>
        </div>
    </div>
</article>