routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    $promotions = \App\Models\Promotion::orderBy('ref', 'desc')->get();

    $promotions = $promotions->filter(function ($promo, $key) {
        return $promo->products()->get()->count() > 1;
    })->take(2);

    return view('pages/home', compact('promotions'));

})->name('home');

Route::get('promocions', function () {

    $promotions = \App\Models\Promotion::orderBy('ref', 'desc')->get();

    return view('pages/promotions', compact('promotions'));

})->name('promotions');

Route::get('contacte', function () {

    return view('pages/contact');

})->name('contact');

Route::get('nosaltres', function () {
    
    return view('pages/about-us');

})->name('about-us');

Route::get('filtre', function () {

    $s = request()->all();

    $q = \App\Models\Product::where('mode', '=', (isset($s['mode'])) ? 'rent' : 'buy');

    if(isset($s['ref']))
    {
        $q = $q->where('external_src_reference', 'LIKE', '%' . $s['ref'] . '%');
    }

    if(isset($s['cities']) && count($s['cities']) > 0)
    {
        $q = $q->whereIn('city_id', array_map('intval', $s['cities']));
    }

    if(isset($s['types']) && count($s['types']) > 0)
    {
        $q = $q->whereIn('type_id', array_map('intval', $s['types']));
    }

    if(isset($s['extras']) && count($s['extras']) > 0)
    {
        foreach($s['extras'] as $extra)
        {
            if(in_array($extra, array_keys(config('site.extras'))))
            {
                $q = $q->where('extras->'. $extra , true);
            }
        }        
    }

    if(isset($s['option-room']))
    {
        $min = (int) explode('-', $s['option-room'])[1];
        $q = $q->where('external_src_rooms', '>=', $min);
    }

    if(isset($s['option-bathroom']))
    {
        $min = (int) explode('-', $s['option-bathroom'])[1];
        $q = $q->where('external_src_bathrooms', '>=', $min);
    }

    $results = $q->get();

    return view('pages/results', ['results' => $results]);

})->name('filter');

Route::get('analyze', function () {
    
    Artisan::call('product:refresh');

    // parsing file
    $url = env('PRODUCTS_XML_PATH', public_path('service/500212.xml'));
    $fileContents = file_get_contents($url);
    $fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
    $fileContents = trim(str_replace('"', "'", $fileContents));
    $simpleXml = simplexml_load_string($fileContents, "SimpleXMLElement", LIBXML_NOCDATA);
    $json = json_encode($simpleXml);
    $object = json_decode($json);
    $inmuebles = collect($object->Inmuebles->Inmueble);

    dump($inmuebles);

});

Route::get('test', function () {
    
    dump(App\Models\Promotion::all()->last()->image);

});


// keep this route last

Route::get('/{slug}/{ref}', function ($slug, $ref) {

    $product = \App\Models\Product::where('external_src_reference', $ref)->firstOrFail();

    if($slug != $product->slug)
        return redirect(route('product', ['slug' => $product->slug, 'ref' => $ref]));

    return view('pages/product', compact('product'));

})->name('product');

app/Models/Product.php
<?php

namespace App\Models;

use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Hamcrest\Type\IsString;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use CrudTrait;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'products';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    protected $guarded = ['id'];
    // protected $hidden = [];
    // protected $dates = [];


    protected $casts = [
        'external_src_object' => 'object'
    ];

    protected $fillable = [
        'mode',
        'city_id',
        'type_id',
        'title',
        'slug',
        'highlighted',
        'extras',
        'description',
        'external_src_reference',
        'external_src_price',
        'external_src_area',
        'external_src_rooms',
        'external_src_bathrooms',
        'external_src_object',
        'promotion_id',
    ];

    public function city()
    {
        return $this->belongsTo(City::class);
    }

    public function type()
    {
        return $this->belongsTo(Type::class);
    }

    public function getPreTitleAttribute()
    {
        return json_decode($this->external_src_object)->LanguageData->Language[1]->txt_Cabecera1;
    }

    public function getDetailsAttribute()
    {
        return json_decode($this->external_src_object)->LanguageData->Language[1]->txt_Detalle1;
    }

    public function getImagesAttribute()
    {
        $images = json_decode($this->external_src_object)->Medias->Fotos->Foto;
        
        if(is_string($images)) {
            return array($images);
        }

        return $images;
    }

    public function getExternalTxt($prop)
    {
        if(
            isset(json_decode($this->external_src_object)->LanguageData->Language[1]->{"txt_$prop"})
            &&
            is_string(json_decode($this->external_src_object)->LanguageData->Language[1]->{"txt_$prop"})
            )
        {
            return json_decode($this->external_src_object)->LanguageData->Language[1]->{"txt_$prop"};
        }

        return null;
    }

    public function getImageAttribute()
    {
        return $this->images[0];
    }

    public function getVideoAttribute()
    {
        // checks exostence of video URL and parses
        // the VIDEO_ID parameter to convert conventional
        // YouTube URL to embedable

        if(isset(json_decode($this->external_src_object)->Medias->Videos->Video)){
            if(isset(parse_url(json_decode($this->external_src_object)->Medias->Videos->Video)['query'])) {
                $query = parse_url(json_decode($this->external_src_object)->Medias->Videos->Video)['query'];

                parse_str($query, $params);

                if(isset($params['v'])) {
                    return 'https://www.youtube.com/embed/'.$params['v'];
                }
            }
        }

        return false;
    }


}

resources/views/pages/contact.blade.php
@extends('layouts.main')
@section('title', 'Contacte |')
@section('main-content')
<div class="bg-secondary rounded-top-lg py-5">
    <div class="container text-center">

        <h1 class="text-white display-4">Sempre a punt <br> per obrir—vos la porta</h1>

        <div class="row justify-content-center">
            <div class="col col-lg-5">
                <div class="py-3">
                    <p>
                        MGO t’ho posa fàcil! <br>
                        Situats al centre de Vic, vine a visitar-nos quan vulguis a les nostres oficines. El nostre equip t’escoltarà, t’assessorà i t’acompanyarà en tots els processos de compra, venda o lloguer d’un immoble.
                    </p>
                </div>
            </div>
        </div>

        <div class="row justify-content-center">
            <div class="col-12 col-lg-3">
                <span class="h5 font-weight-bold">Dl a Dv <br>
                    9.30h a 19.30h
                </span>
            </div>
            <div class="col-12 d-lg-none">
                <div class="border-white mt-2 mb-2 border-top"></div>
            </div>
            <div class="col-12 col-lg-3 border-white border-lg-left">
                <span class="h5 font-weight-bold">Ds <br>
                    9.00h a 12.00h
                </span>
            </div>
        </div>
    </div>
</div>
<div class="position-relative">
    <div class="bg-secondary d-none d-lg-block" style="width: 100%; height: 50%; position: absolute; top: 0; left: 0;"></div>
    <div class="text-center container-only-lg">
        <div class="row no-gutters d-flex justify-content-center align-items-center">

            <div class="col-lg">
                <div id="mapa">
                    <img src="{{ asset('images/mapa.svg') }}" alt="" style="">
                    <a href="#" class="marker"></a>
                    <span class="font-brand-alt font-brand-alt-1 label">Plaça major <br> de Vic</span>
                </div>
            </div>
            <div class="col-4 col-lg-2 order-lg-first pr-lg-2 t-m20">
                <div class="circle-outline ml-auto">
                    <script type="text/javascript">part1='hola@'; part2='mgo.cat'; emailE=(part1 + part2); document.write('<a href="mailto:' + emailE + '" class="d-block inner-text h5 font-weight-bold a-clean">' + part1 + '<br>' + part2 + '</a>');</script>
                </div>
            </div>
            <div class="col-4 col-lg-2 pl-lg-2 t-m20">
                <div class="circle-outline mr-auto">
                    <span class="d-block h5 inner-text font-weight-bold">Tel. <br><a href="tel:+34938866165" class="a-clean">938 866 165</a></span>
                </div>
            </div>

        </div>
    </div>
</div>
<div class="pb-5"></div>
<div class="py-5 bg-gray rounded-top-lg">
    <div class="container">
    @include('inc/form', ['options' => config('site.contact-form-options')])
    </div>
</div>



@endsection

resources/views/pages/home.blade.php
@extends('layouts.main')

@section('main-content')
    <div class="bg-gray rounded-top-lg search-module">
        @include('sections/search', ['parent_id' => 'home-search'])
    </div>

    @if($promotions->count() > 0)
    <div class="pt-4 pb-4 pb-lg-0 bg-light-blue">
        @include('sections/promotions')
    </div>
    @endif

    <div class="@if($promotions->count() > 0) bg-light-blue @else bg-gray @endif">
        @include('sections/properties')
    </div>

    <div class="py-4">
        @include('sections/help')
    </div>

    <div class="py-4 bg-green rounded-top-lg">
        @include('sections/about-us')
    </div>
@endsection

resources/views/pages/product.blade.php
@extends('layouts.main')
@section('title', $product->pre_title . ' — ' . $product->title . ' — ' . $product->city()->first()->label . ' | ')
@section('main-content')
<div class="bg-gray pt-2 rounded-top">

    <div class="container">

        <ul class="nav nav-pills justify-content-center pt-1" role="tablist">
            <li class="nav-item px-05 px-lg-1" role="presentation">
                <a class="btn btn-nav btn-outline-primary btn-override active" id="pills-photos-tab" data-toggle="pill" href="#pills-photos" role="tab" aria-controls="pills-photos" aria-selected="true">
                    <div class="icon">
                        @php include(public_path('images/icons/icon-camera.svg')) @endphp
                        <span>Fotos</span>
                    </div>
                </a>
            </li>
            @if($product->video)
            <li class="nav-item px-05 px-lg-1" role="presentation">
                <a class="btn btn-nav btn-outline-primary btn-override" id="pills-video-tab" data-toggle="pill" href="#pills-video" role="tab" aria-controls="pills-video" aria-selected="false">
                    <div class="icon">
                        @php include(public_path('images/icons/icon-video.svg')) @endphp
                        <span>Video</span>
                    </div>
                </a>
            </li>
            @endif
            <li class="nav-item px-05 px-lg-1" role="presentation">
                <a class="btn btn-nav btn-outline-primary btn-override" id="pills-360-tab" data-toggle="pill" href="#pills-360" role="tab" aria-controls="pills-360" aria-selected="false">
                    <div class="icon">
                        @php include(public_path('images/icons/icon-360.svg')) @endphp
                        <span>360°</span>
                    </div>
                </a>
            </li>
        </ul>

    </div>

    <div class="tab-content py-3" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-photos" role="tabpanel" aria-labelledby="pills-photos-tab">
            <div id="slider-images">
                @foreach ($product->images as $image)
                <div class="slide">
                    <div class="container">
                        <div class="rounded overflow-hidden">
                            <img src="{{ $image }}" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col col-xl-10">
                        <div class="text-center py-2 d-flex justify-content-center">
                            <div class="">
                                <img src="{{ asset('images/arrow-left.svg') }}" alt="" style="width: 20px;">
                            </div>
                            <div class="px-2">
                                <span class="font-brand-alt font-brand-alt-1">Desplaça</span>
                            </div>
                            <div class="">
                                <img src="{{ asset('images/arrow-right.svg') }}" alt="" style="width: 20px;">
                            </div>
                        </div>
                        <div id="slider-images-nav" class="slider">
                            @foreach ($product->images as $image)
                            <div class="item">
                                <div class="rounded-sm overflow-hidden">
                                    <img src="{{ $image }}" alt="" class="img-fluid">
                                </div>
                            </div>
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane fade" id="pills-video" role="tabpanel" aria-labelledby="pills-video-tab">
            @if($product->video)
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col">
                        <div class="embed-responsive embed-responsive-16by9">
                            <iframe class="embed-responsive-item" src="{{ $product->video }}" allowfullscreen></iframe>
                        </div>
                    </div>
                </div>
            </div>
            @endif
        </div>
        <div class="tab-pane fade" id="pills-360" role="tabpanel" aria-labelledby="pills-360-tab">
            <div class="container">
                <div class="row justify-content-center ">
                    <div class="col text-center py-5">
                        <div class="py-5 bg-white font-brand-alt font-brand-alt-1">
                            <div class="py-5">
                            Aviat disponible!
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="bg-light-blue py-5">
        <div class="container">
            <h1 class="h4 font-weight-bold mb-4 text-center text-lg-left"> {{ $product->pre_title }} {{ ' — ' . $product->city()->first()->label }}</h1>

            <div class="row">
                <div class="col-lg-5 text-center">

                    <div class="row no-gutters font-brand-alt font-brand-alt-1 mb-3 mb-lg-0">
                        <div class="col">
                            Ref.
                            <br>
                            <span class="d-block font-brand-alt-2 mt-1">{{ $product->external_src_reference }}</span>
                        </div>
                        <div class="col border-left border-primary">
                            M<sup class="small font-weight-bold">2</sup>
                            <br>
                            <span class="d-block font-brand-alt-2 mt-1">{{ $product->external_src_area }}</span>
                        </div>
                        <div class="col border-left border-primary">
                            Hab.
                            <br>
                            <span class="d-block font-brand-alt-2 mt-1">{{ $product->external_src_rooms }}</span>
                        </div>
                        <div class="col border-left border-primary">
                            WC
                            <br>
                            <span class="d-block font-brand-alt-2 mt-1">{{ $product->external_src_bathrooms }}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-7 order-lg-first">
                    <div class="content text-center text-lg-left">
                        {{ $product->details }}
                    </div>
                </div>
            </div>
        </div>
        <div class="py-1"></div>
    </div>
    <div class="text-center translate-m50">
        <a href="https://api.whatsapp.com/send?phone=+34938866165&text=Hola, voldria infromació sobre aquest immoble. Referència {{ $product->external_src_reference }}!" class="btn btn-primary btn-override" target="_blank"> Parlem-ne </a>
    </div>
</div>

<div class="py-3 py-lg-5" id="product-specs">
    <div class="container">
        <h2 class="h4 font-weight-bold mb-4"> Característiques </h2>
        <div class="row font-brand-alt font-brand-alt-1">
            <div class="col-12 col-lg-6">

                <div class="dotted-line-h w-100 mb-1"></div>

                @if(is_string(json_decode($product->external_src_object)->LanguageData->Language[1]->txt_AnoConstruccion))
                <div class="row no-gutters">
                    <div class="col-12 col-md-6 pl-md-1">Any de construcció</div>
                    <div class="col-12 col-md-6">{{ json_decode($product->external_src_object)->LanguageData->Language[1]->txt_AnoConstruccion }}</div>
                </div>
                <div class="dotted-line-h w-100 my-1"></div>
                @endif

                @if(json_decode($product->external_src_object)->box_CertificacionEnergeticaEnTramite == 'Disponible')
                <div class="row no-gutters">
                    <div class="col-12 col-md-6 pl-md-1">Certificació energètica</div>
                    <div class="col-12 col-md-6">                    
                        <div class="px-05 text-nowrap">
                            <img src="{{ asset('images/ce/ce-'.json_decode($product->external_src_object)->box_CertificacionEnergetica.'.png' )}}" alt="" style="width: 28px;" class="pr-1">
                            Consum {{ json_decode($product->external_src_object)->box_PrestacionEnergetica }} kwh/m<sup>2</sup> any <br>
                        </div>
                        <div class="px-05 text-nowrap">
                            <img src="{{ asset('images/ce/ce-'.json_decode($product->external_src_object)->box_CertificacionEmisiones.'.png' )}}" alt="" style="width: 28px;" class="pr-1">
                            Emisions {{ json_decode($product->external_src_object)->box_PrestacionEmisiones }} kg CO<sub>2</sub>/m<sup>2</sup> any<br>
                        </div>
                    
                    </div>
                </div>
                @else
                <div class="row no-gutters">
                    <div class="col-12 col-md-6 pl-md-1">Certificació energètica</div>
                    <div class="col-12 col-md-6">
                        {{ json_decode($product->external_src_object)->box_CertificacionEnergeticaEnTramite }}
                    </div>
                </div>
                @endif

                <div class="dotted-line-h w-100 mt-1"></div>

            </div>

            <div class="col-12 col-lg-6">

                <div class="dotted-line-h w-100 mb-1"></div>

                @if(!is_null($product->getExternalTxt('Calefaccion')))
                <div class="row no-gutters">
                    <div class="col-12 col-md-6 pl-md-1">Calefacció</div>
                    <div class="col-6">{{ $product->getExternalTxt('Calefaccion') }}</div>
                </div>
                <div class="dotted-line-h w-100 my-1"></div>
                @endif

                @if(!is_null($product->getExternalTxt('CarpinteriaExterior')))
                <div class="row no-gutters">
                    <div class="col-12 col-md-6 pl-md-1">Carpinteria Exterior</div>
                    <div class="col-12 col-md-6">{{ $product->getExternalTxt('CarpinteriaExterior') }}</div>
                </div>
                <div class="dotted-line-h w-100 my-1"></div>
                @endif

                @if($product->getExternalTxt('CarpinteriaInterior'))
                <div class="row no-gutters">
                    <div class="col-12 col-md-6 pl-md-1">Carpinteria Interior</div>
                    <div class="col-12 col-md-6">{{ $product->getExternalTxt('CarpinteriaInterior') }}</div>
                </div>
                <div class="dotted-line-h w-100 mt-1"></div>
                @endif

                {{--
                <div class="">
                    <div class="row no-gutters">
                        <div class="col-6 pl-1">Etiquetes</div>
                        <div class="col-6">Fletxa</div>
                    </div>
                    <ul id="product-tags" class="list-unstyled pt-2 pl-2">
                        <li>Etiqueta 1</li>
                        <li>Etiqueta 2</li>
                        <li>Etiqueta 3</li>
                    </ul>
                </div>
                <div class="dotted-line-h w-100 my-1"></div>
                --}}

            </div>

        </div>
    </div>
</div>

<div class="py-5 bg-yellow rounded-top-lg">
    <div class="container">
    @include('inc/form', ['options' => config('site.product-form-options')])
    </div>
</div>

@endsection

resources/views/pages/promotions.blade.php
@extends('layouts.main')
@section('title', 'Promocions |')
@section('main-content')
    <div class="rounded-top-lg pt-4 bg-light-blue">
        @include('sections/promotions')
    </div>
@endsection

resources/views/pages/results.blade.php
@extends('layouts.main')
@section('title', 'Cerca immobles |')
@section('main-content')
<div class="bg-green rounded-top-lg search-module has-advanced-filters">
    @include('sections/search', ['advanced' => true, 'parent_id' => 'results'])
</div>
<div class="container">
    <div class="text-center pt-4">
        <h5 class="m-0">{{ count($results) }} {{ Illuminate\Support\Str::plural('resultat', count($results)) }}</h5>
    </div>
    <div id="results" class="row no-gutters pt-4">
        @foreach ($results as $item)
        <div class="result-wrapper col-12 col-lg-4 pb-3">
            <div class="result">
                <div class="result-inner-wrapper pb-3 pb-lg-0">
                    @include('inc/property/article', ['article' => $item])
                </div>
            </div>
        </div>
        @endforeach
    </div>
</div>
@endsection